$('.owl-carouselP').owlCarousel({
  loop:true,
  margin:10,
  loop:true,
  nav:false,
  autoplay:true,
  autoplayTimeout:2000,
  autoplayHoverPause:true,
  responsive:{
      0:{
          items:1
      },
      600:{
          items:3
      },
      1000:{
          items:8
      }
  }
})

$('.owl-carouselS').owlCarousel({
    loop:true,
    margin:10,
    loop:true,
    nav:false,
    autoplay:true,
    autoplayTimeout:2500,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:8
        }
    }
  })